### PR TITLE
Updated ExplodedBlockManager.java

### PR DESCRIPTION
**Pull request by UltraFireFX**

### CODE REVIEW

**Comment by nitnelave** [comment]
The commit message needs to be more specific (what changed? why?). Maybe mention compatibility with a certain Java version? I don't remember which one is needed for Bukkit.

**Comment by nitnelave** [comment]
Oh, and make sure this is the only place that needs to be changed for this.

**Comment by UltraFireFX** [comment]
Ohh, sorry about that, it's not a major if the plugin was coded correctly (which it looks like it was), it's just to clear up a Java warning.

**Comment by nitnelave** [comment]
The warning depends on how you configured your IDE, but sure.

**Pull request closed without merging**
